"""Add about_me column to User model

Revision ID: 28210929fc8d
Revises: 62ad398561bc
Create Date: 2024-02-16 16:36:52.177877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28210929fc8d'
down_revision = '62ad398561bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))

    # ### end Alembic commands ###
    op.add_column('user', sa.Column('product_type', sa.String(length=100), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
